<?php

/**
 * crpTag
 *
 * @copyright (c) 2008-2010 Daniele Conca
 * @link http://code.zikula.org/crptag Support and documentation
 * @author Daniele Conca <conca.daniele@gmail.com>
 * @license GNU/GPL - v.2.1
 * @package crpTag
 */

/**
 * initialise block
 *
 */
function crpTag_tagsblock_init()
{
	// Security
	pnSecAddSchema('Tagsblock::', 'Block title::');
}

/**
 * get information on block
 *
 */
function crpTag_tagsblock_info()
{
	return array (
		'text_type' => 'crpTags',
		'module' => 'crpTag',
		'text_type_long' => 'Collection of site tags',
		'allow_multiple' => true,
		'form_content' => false,
		'form_refresh' => false,
		'show_preview' => true
	);
}

/**
 * display block
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function crpTag_tagsblock_display($blockinfo)
{
	// security check
	if (!SecurityUtil :: checkPermission('Tagsblock::', "$blockinfo[title]::", ACCESS_READ))
		return;

	if (!pnModAvailable('crpTag'))
		return;

	// get the current language
	$currentlang = ZLanguage::getLanguageCode();

	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);
	// get all module vars for later use
	$modvars = pnModGetVar('crpTag');

	$apiargs['startnum'] = 1;
	$apiargs['numitems'] = $modvars['tag_itemsperpage'];
	$apiargs['extended'] = true;
	$apiargs['groupbyname'] = true;
	$apiargs['interval'] = $vars['interval'];

	// call the api
	$items = pnModAPIFunc('crpTag', 'user', 'gettags', $apiargs);

	// create the output object
	$render = & pnRender :: getInstance('crpTag', false);

	$render->assign('tags', $items);
	$render->assign($modvars);
	$render->assign('showcounter', $vars['showcounter']);
	$render->assign('interval', $vars['interval']);

	$blockinfo['content'] = $render->fetch('blocks/crptag_block_tags_cloud.htm');

	return pnBlockThemeBlock($blockinfo);
}

/**
 * modify block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function crpTag_tagsblock_modify($blockinfo)
{
	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// Create output object
	$render = & pnRender :: getInstance('crpTag', false);

	// assign the block vars
	$render->assign($vars);

	// Return the output that has been generated by this function
	return $render->fetch('blocks/crptag_block_tags_cloud_modify.htm');

}

/**
 * update block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function crpTag_tagsblock_update($blockinfo)
{
	// Get current content
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// alter the corresponding variable
	$vars['showcounter'] = FormUtil :: getPassedValue('showcounter', null);
	$vars['interval'] = FormUtil :: getPassedValue('interval', null);

	// write back the new contents
	$blockinfo['content'] = pnBlockVarsToContent($vars);

	// clear the block cache
	$render = & pnRender :: getInstance('crpTag');
	$render->clear_cache('blocks/crptag_block_tags_cloud.htm');

	return $blockinfo;
}
?>