<?php
/**
 * crpTag
 *
 * @copyright (c) 2008-2009 Daniele Conca
 * @link http://code.zikula.org/crptag Support and documentation
 * @author Daniele Conca <conca.daniele@gmail.com>
 * @license GNU/GPL - v.2.1
 * @package crpTag
 */

/**
 * initialise block
 *
 */
function crpTag_tagsphereblock_init()
{
	// Security
	pnSecAddSchema('Tagsblock::', 'Block title::');
}

/**
 * get information on block
 *
 */
function crpTag_tagsphereblock_info()
{
	return array (
		'text_type' => 'crpTags',
		'module' => 'crpTag',
		'text_type_long' => 'A sphere of site tags',
		'allow_multiple' => true,
		'form_content' => false,
		'form_refresh' => false,
		'show_preview' => true
	);
}

/**
 * display block
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function crpTag_tagsphereblock_display($blockinfo)
{
	// security check
	if (!SecurityUtil :: checkPermission('Tagsblock::', "$blockinfo[title]::", ACCESS_READ))
		return;

	if (!pnModAvailable('crpTag'))
		return;

	// get the current language
	$currentlang = pnUserGetLang();

	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);
	// get all module vars for later use
	$modvars = pnModGetVar('crpVideo');

	$apiargs['startnum'] = 1;
	$apiargs['numitems'] = $modvars['tag_itemsperpage'];
	$apiargs['extended'] = true;
	$apiargs['groupbyname'] = true;
	$apiargs['interval'] = $vars['interval'];

	// call the api
	$items = pnModAPIFunc('crpTag', 'user', 'gettags', $apiargs);

	// create the output object
	$pnRender = pnRender :: getInstance('crpTag', false);

	$pnRender->assign('tags', $items);
	$pnRender->assign($modvars);
	$pnRender->assign('showcounter', $vars['showcounter']);
	$pnRender->assign('interval', $vars['interval']);
	$pnRender->assign('sphere_width', $vars['sphere_width']);
	$pnRender->assign('sphere_height', $vars['sphere_height']);

	$flashtags = '<tags>';
  foreach ($items as $item) {
  	$itemurl = pnModUrl("crpTag","user","display",array('id'=>$item['id']));
    // assign font size
    $style = 'font-size:'.(10+$item['avg']).'%;';
    if ($item['avg'] > 2)
    	$style .= 'font-weight:bold;';
    $flashtags .= '<a style="'.$style.'" href="'.$itemurl.'" title="'._VIEW.' '.$item['name'].'" rel="tag">'.$item['name'];
    if ($vars['showcounter'])
    	$flashtags .= ' ('.$item['tagcounter'].')';
    $flashtags .= '</a>';
  }
  $flashtags .= '</tags>';
  $flashtags = urlencode($flashtags);
  $pnRender->assign('flashtags', $flashtags);

	$blockinfo['content'] = $pnRender->fetch('blocks/crptag_block_tagsphere_cloud.htm');

	return pnBlockThemeBlock($blockinfo);
}

/**
 * modify block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function crpTag_tagsphereblock_modify($blockinfo)
{
	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// Create output object
	$pnRender = pnRender :: getInstance('crpTag', false);

	// assign the block vars
	$pnRender->assign($vars);

	// Return the output that has been generated by this function
	return $pnRender->fetch('blocks/crptag_block_tagsphere_cloud_modify.htm');

}

/**
 * update block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function  crpTag_tagsphereblock_update($blockinfo)
{
	// Get current content
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// alter the corresponding variable
	$vars['showcounter'] = FormUtil :: getPassedValue('showcounter', null);
	$vars['interval'] = FormUtil :: getPassedValue('interval', null);
	$vars['sphere_width'] = FormUtil :: getPassedValue('sphere_width', 200);
	$vars['sphere_height'] = FormUtil :: getPassedValue('sphere_height', 200);

	// write back the new contents
	$blockinfo['content'] = pnBlockVarsToContent($vars);

	// clear the block cache
	$pnRender = pnRender :: getInstance('crpTag');
	$pnRender->clear_cache('blocks/crptag_block_tagsphere_cloud.htm');

	return $blockinfo;
}
?>