<?php

/**
 * crpTag
 *
 * @copyright (c) 2008-2010 Daniele Conca
 * @link http://code.zikula.org/crptag Support and documentation
 * @author Daniele Conca <conca.daniele@gmail.com>
 * @license GNU/GPL - v.2.1
 * @package crpTag
 */

/**
 * initialise block
 *
 */
function crpTag_tagsphereblock_init()
{
	// Security
	pnSecAddSchema('Tagsblock::', 'Block title::');
}

/**
 * get information on block
 *
 */
function crpTag_tagsphereblock_info()
{
	return array (
		'text_type' => 'crpTags',
		'module' => 'crpTag',
		'text_type_long' => 'A sphere of site tags',
		'allow_multiple' => true,
		'form_content' => false,
		'form_refresh' => false,
		'show_preview' => true
	);
}

/**
 * display block
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function crpTag_tagsphereblock_display($blockinfo)
{
	// security check
	if (!SecurityUtil :: checkPermission('Tagsblock::', "$blockinfo[title]::", ACCESS_READ))
		return;

	if (!pnModAvailable('crpTag'))
		return;

	// get the current language
	$currentlang = ZLanguage::getLanguageCode();
	$dom = ZLanguage::getModuleDomain('crpTag');

	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);
	// get all module vars for later use
	$modvars = pnModGetVar('crpTag');

	$apiargs['startnum'] = 1;
	$apiargs['numitems'] = $modvars['tag_itemsperpage'];
	$apiargs['extended'] = true;
	$apiargs['groupbyname'] = true;
	$apiargs['interval'] = $vars['interval'];

	// call the api
	$items = pnModAPIFunc('crpTag', 'user', 'gettags', $apiargs);

	// create the output object
	$render = & pnRender :: getInstance('crpTag', false);

	$render->assign('tags', $items);
	$render->assign($modvars);
	$render->assign('showcounter', $vars['showcounter']);
	$render->assign('interval', $vars['interval']);
	$render->assign('sphere_width', $vars['sphere_width']);
	$render->assign('sphere_height', $vars['sphere_height']);

	$flashtags = '<tags>';
	foreach ($items as $item)
	{
		$itemurl = pnModUrl("crpTag", "user", "display", array (
			'id' => $item['id']
		), null, null, null, true);
		// assign font size
		$style = 'font-size:' . (10 + 2*(int)($item['avg'])) . 'pt;';
		if ((int)($item['avg']) > 10)
			$style .= 'font-weight:bold;';
		$flashtags .= "<a href='" . $itemurl . "' style='" . $style . "' title='" . __('View', $dom) . ' ' . $item['name'] . "' rel='tag'>" . $item['name'];
		if ($vars['showcounter'])
			$flashtags .= ' (' . $item['tagcounter'] . ')';
		$flashtags .= '</a>';
	}
	$flashtags .= '</tags>';
	$flashtags = urlencode($flashtags);
	$render->assign('flashtags', $flashtags);

	$blockinfo['content'] = $render->fetch('blocks/crptag_block_tagsphere_cloud.htm');

	return pnBlockThemeBlock($blockinfo);
}

/**
 * modify block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function crpTag_tagsphereblock_modify($blockinfo)
{
	// Break out options from our content field
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// Create output object
	$render = & pnRender :: getInstance('crpTag', false);

	// assign the block vars
	$render->assign($vars);

	// Return the output that has been generated by this function
	return $render->fetch('blocks/crptag_block_tagsphere_cloud_modify.htm');

}

/**
 * update block settings
 *
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function crpTag_tagsphereblock_update($blockinfo)
{
	// Get current content
	$vars = pnBlockVarsFromContent($blockinfo['content']);

	// alter the corresponding variable
	$vars['showcounter'] = FormUtil :: getPassedValue('showcounter', null);
	$vars['interval'] = FormUtil :: getPassedValue('interval', null);
	$vars['sphere_width'] = FormUtil :: getPassedValue('sphere_width', 200);
	$vars['sphere_height'] = FormUtil :: getPassedValue('sphere_height', 200);

	// write back the new contents
	$blockinfo['content'] = pnBlockVarsToContent($vars);

	// clear the block cache
	$render = & pnRender :: getInstance('crpTag');
	$render->clear_cache('blocks/crptag_block_tagsphere_cloud.htm');

	return $blockinfo;
}
?>